/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGrafica;

import ClassesPedido.Servico;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;

import Utils.AcessFile;

/**
 *
 * @author Loures
 */
public class Lista extends javax.swing.JPanel {
    private char tipoLista;
    private char tipoUsuario;
    private ArrayList<Servico> servico_list;
    private DefaultListModel model;
    
    public Lista(char tipoLista, char tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
        model = new DefaultListModel();
        ArrayList<Servico> servico_list = AcessFile.lista_servicos_all();
        for(int i=0; i<servico_list.size(); i++) {
            model.add(i, servico_list.get(i).getNome());
        }
        
        initComponents();
        this.setVisible(true);
        this.tipoLista = tipoLista;
        if(tipoLista == 's') {
            jLabel1.setText("Lista de serviços");
            //ArrayList<Servico> servico_list = AcessFile.lista_servicos_all();
        }
        else 
           jLabel1.setText("Lista de pedidos");
        
        jButton1.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jList1.setModel(model);
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jButton1.setText("Habilitar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Lista de");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                        .addGap(37, 37, 37)
                        .addComponent(jButton1)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(137, 137, 137))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if(tipoUsuario == 'a') {
            if(tipoLista == 's'){
                int indice = jList1.getSelectedIndex();
                servico_list = AcessFile.lista_servicos_all();
                AcessFile.alterar_status_servico(servico_list.get(indice).getNome(), true);
                System.out.println("Alterado!");
                /*
                //Bloco abaixo é pra teste
                model = new DefaultListModel();
                servico_list = AcessFile.lista_servicos_all();
                for(int i=0; i<servico_list.size(); i++) {
                    model.add(i, servico_list.get(i).getNome());
                }
                */
                for(int i = 0; i < jList1.getModel().getSize(); i++) {
                    if(i == indice) {
                        //texto = jList1.getSelectedValue().contains("Habilitado") ? jList1.getSelectedValue().replace("Habilitado", "Desabilitado") : jList1.getSelectedValue().replace("Desabilitado", "Habilitado");
                    } else {
                        //modelo.addElement(jList1.getModel().getElementAt(i));
                    }
                }
                //jList1.setModel(modelo);
                // salvar a nova jList no arquivo
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        jButton1.setEnabled(jList1.getSelectedIndex() != -1);
        if(tipoUsuario == 'a'){
            if(tipoLista == 's'){
                String texto = jList1.getSelectedValue().contains("Habilitado") ? "Desabilitar" : "Habilitar";
                jButton1.setText(texto);
            }
        }
    }//GEN-LAST:event_jList1ValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
